![logo_usjt.png](https://www.usjt.br/app/themes/mobister/dist/images/sao-judas-universidade.png)

# Gerenciamento de Dados e Informação
- **Professor**: Sergio Bonato <antonio.bonato@saojudas.br>

# Atividade04 - NumPy Básico: Arrays e Processamento Vetorizado

**Conteúdo:**
- O que é NumPy; NumPy arrays; operações com arrays
- NumPy: matrizes e operações com matrizes
- NumPy: carregando dados com NumPy
- NumPy: álgebra linear básica

## Autor
**Aluno: **

Obs: esta atividade é individual.

## Exercícios

**1** Utilize o código dado para importar o arquivo `dados.csv`, que contém dados de saúde sobre homens e mulheres de diversas idades. Veja na tabela a descrição dos campos.

|Ordem|Campo|Descrição|
|:-|:-|:-|
|0|sexo|Homem=0 Mulher=1|
|1|idade|anos completos|
|2|rendom|renda domiciliar|
|3|anoest|anos de estudo|
|4|altura||
|5|peso||
|6|probagud|0 não teve problemas nos últimos 30 dias, 1 = teve problema nos últimos 30 dias|
|7|probcron|0 não tem problemas crônicos, 1 = tem problemas crônicos|
|8|gastorem|gasto com medicamentos nos últimos 30 dias|

Utilize o código pronto para importar os dados. Veja que o parâmetro `converters` da função `loadtxt` contém um dicionário que converte os dados faltantes para `nan` (not a number).

In [2]:
#para importar arquivos do Google Drive
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [276]:
import numpy as np

#coloque aqui o caminho completo do arquivo
arquivo = '/content/gdrive/My Drive/Classroom/DataWarehousing e Data Mining USJT_2020 1 - CCPELVN-MCA/dados.csv'
headers = np.array(['sexo', 'idade', 'rendom', 'anoest', 'altura', 'peso', 'probagud', 'probracron', 'gastorem'])
zera = lambda x: np.nan if len(x)==0 else x
conversores = {i:zera for i in range(9)}
arr = None
arr = np.loadtxt(drive.mount("/content/gdrive", force_remount=True))

Mounted at /content/gdrive


ValueError: ignored

**a)** Imprima o formato do array arr.

In [277]:
#solucao
print(headers.dtype)

<U10


**b)** Imprima as 10 primeiras linhas do vetor e examine-as.

In [278]:
#solucao
print(headers)

['sexo' 'idade' 'rendom' 'anoest' 'altura' 'peso' 'probagud' 'probracron'
 'gastorem']


**c)** Verifique se há colunas com dados nan. Quais são as colunas? Dicas: use o array headers definido no código dado, a ufunction `isnan()` e a função `any()`, um loop `for` e indexação booleana.

In [281]:
#solucao
np.isnan(np.nan)
np.any(np.nan)

True

**d)** Crie uma visão do array arr sem as linhas que contém anotações faltantes (dados nan).

In [0]:
#solucao
headers = np.array

**e)** Calcule a média de cada coluna da visão not_nan e atribua aos nan da coluna altura a média da altura e aos nan da coluna peso a média da coluna peso. Antes da trocar os nan, calcule a média das colunas de arr para ver o que acontece. 

Lembre-se de como funcionam os eixos! Abaixo um exemplo com a função `sum()`
![eixos](https://saskeli.github.io/data-analysis-with-python-summer-2019/_images/aggregation.svg)

In [0]:
#solução

**f)** calcule agora a média, o desvio padrão, o máximo e o mínimo de todas as colunas do array sem filtro

In [0]:
#solução

**2** Escreva duas funções, `get_rows` e `get_columns`, que recebem um array bidimensional como parâmetro. Elas devem retornar uma lista de linhas e colunas do array, respectivamente. As linhas e colunas devem ser matrizes unidimensionais. Você pode usar a operação de transposição, que inverte linhas para colunas, em sua solução. A transposição é feita pelo método `T`.

In [156]:
#exemplo
a=np.random.randint(0, 10, (4,4))
print(a)
print(a.T)

[[2 8 9 6]
 [8 5 5 1]
 [2 4 5 7]
 [7 1 7 9]]
[[2 8 2 7]
 [8 5 4 1]
 [9 5 5 7]
 [6 1 7 9]]


In [0]:
#solução
def get_rows(m):
    return m[i:]

In [0]:
#solução
def get_columns(m):
    return m[:]

In [0]:
#teste - dados
a = np.array([[5, 0, 3, 3],
              [7, 9, 3, 5],
              [2, 4, 7, 6],
              [8, 8, 1, 6]])

In [146]:
#teste row
print(get_rows(a))
#[array([5, 0, 3, 3]), array([7, 9, 3, 5]), array([2, 4, 7, 6]), array([8, 8, 1, 6])]

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]


In [227]:
#teste column
print(get_columns(a.T))
#[array([5, 7, 2, 8]), array([0, 9, 4, 8]), array([3, 3, 7, 1]), array([3, 5, 6, 6])]

[[5 3]
 [0 7]
 [3 9]]


**3** Crie a função `get_row_vectors` que retorna uma lista de linhas do array de entrada da forma `(n, m)`, mas desta vez as linhas devem ter a forma `(1, m)`. Da mesma forma, crie a função get_columns_vectors que retorne uma lista de colunas (cada uma com forma `(n, 1)`) da matriz de entrada.

Para a entrada:

`[[5 0 3]
 [3 7 9]]`
 
Deve ser gerada a saída:

Vetor de Linhas:

`[array([[5, 0, 3]]), array([[3, 7, 9]])]`

Vetor de Colunas:

`[array([[5],
        [3]]),
 array([[0],
        [7]]),
 array([[3],
        [9]])]`

In [0]:
#solucao row
def get_row_vectors(m):
    return [m]

In [0]:
#solucao column
def get_column_vectors(m):
    m = m.T
    return [m]

In [216]:
#teste - dados
a = np.array([[5, 0, 3],[3, 7, 9]])
a.shape

(2, 3)

In [229]:
#teste row
print(get_row_vectors(a))

[array([[5, 0, 3],
       [3, 7, 9]])]


In [231]:
#test column
print(get_column_vectors(a))

[array([[5, 3],
       [0, 7],
       [3, 9]])]


**4** Crie a função `diamante` que retorne um array inteiro bidimensional em que os 1s formem uma forma de diamante. O restante dos números é 0. A função deve receber um parâmetro que informe o comprimento de um lado do diamante. Faça isso usando as funções `eye` e `concatenate` do NumPy e o fatiamento de array.

Ex:

`print(diamante(3))`

`[[0 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]]`

`print(diamante(1))`

`[[1]]`

In [232]:
#Exemplo do concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [233]:
#Exemplo do concatenate
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [234]:
#Exemplo do concatenate
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [0]:
#solução
def diamante(n):
  
  pass
  np.eye(10).astype(dtype='i8')

In [248]:
#teste
print(diamante(3))

None


In [246]:
#teste
print(diamante(1))

None


**5** Escreva a função lambda `so_pares` que receba um array unidimensional de inteiros e devolva este array sem números ímpares. Dica: use indexação booleana.

Ex:

Entrada: 

`arr = np.array([0,1,2,3,4,5,6,7,8,9])`

Saída:

`array([0, 2, 4, 6, 8])`

In [0]:
#solucao
arr = np.array([0,1,2,3,4,5,6,7,8,9])
so_pares = lambda x: x * 2

vectorize = np.vectorize(so_pares)

In [266]:
#teste
arr = np.arange(5)
print(vectorize(arr))

[0 2 4 6 8]


**6** Escreva a função lambda `cade_os_iguais` que receba dois arrays unidimensionais de inteiros x e y e devolva um array com a(s) posição(ões) em que há números iguais nos dos arrays. Não use `for`. Dica: use np.where

Ex:

Entrada: 

`x = np.array([5,6,7,8,3,4])`

`y = np.array([5,3,4,5,2,4])`

Saída:

`array([0, 5])`

In [0]:
#solucao
x = np.array([5,6,7,8,3,4])
y = np.array([5,3,4,5,2,4])
cade_os_iguais = lambda x: y
np.where(x == y)

vectorize = np.vectorize(cade_os_iguais)

In [275]:
#teste
x = np.array([5,6,7,8,3,4])
y = np.array([5,3,4,5,2,4])
print(vectorize(np.where))

[5 3 4 5 2 4]
